name: CI devops 2026
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
    - main
    - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file ./tp-docker/2-backend/simple-api/pom.xml
  test-sonar: 
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: SonarCloud Scan
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=JulesCinc_dev-ops -Dsonar.organization=julescinc -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./tp-docker/2-backend/simple-api/pom.xml

  build-and-push-backend:
    needs: test-sonar  
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DOCKER
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./tp-docker/2-backend # Le dossier où se trouve le Dockerfile pour l'API
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }} # Push SEULEMENT sur la branche 'main'

  build-and-push-db:
    needs: test-sonar  
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DOCKER
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./tp-docker/1-database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

  build-and-push-httpd:
    needs: test-sonar  
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DOCKER
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./tp-docker/3-httpd
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      


